#ifndef CONST_ENTITY_H
#define CONST_ENTITY_H


#define HAUTEUR_SOL_PLAYER 20.0f
#define MAX_OFFSET_HAUTEUR 1.5f
#define HAUTEUR_PLAYER 10.0f
#define ANGLE_OUVERTURE_TIR 10.0f
#endif // CONST_ENTITY_H
